# Generated by Django 5.0.6 on 2024-06-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='car_image',
        ),
    ]
