# Generated by Django 5.0.6 on 2024-06-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_rename_image_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
