# Generated by Django 5.0.6 on 2024-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_alter_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
