# Generated by Django 5.0.6 on 2024-07-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0004_alter_car_car_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car',
        ),
    ]
